version: "3"

networks:
  dbnet:
    driver: bridge

services:
 
  test:
    build:
      context: .
      dockerfile: springboot-test.dockerfile
    container_name: springbootapptest
    networks:
      - dbnet
